Update explore_actions.yml

diff --git a/.github/workflows/explore_actions.yml b/.github/workflows/explore_actions.yml
--- a/.github/workflows/explore_actions.yml
+++ b/.github/workflows/explore_actions.yml
@@ -1,5 +1,3 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
 
 # Controls when the workflow will run
@@ -25,12 +23,26 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
-      # Runs a single command using the runners shell
+      # Runs a single command using the runner's shell
       - name: Run a one-line script
         run: echo Hello, world!
 
-      # Runs a set of commands using the runners shell
+      # Runs a set of commands using the runner's shell
       - name: Run a multi-line script
         run: |
           echo Add other actions to build,
           echo test, and deploy your project.
+
+      # Introduce a step to simulate an error
+      - name: Simulate a failure
+        run: exit 1
+        continue-on-error: true
+
+      # Handle the error message based on the previous step
+      - name: Error message on failure
+        if: failure()  # Only runs if the previous step fails
+        run: echo "::error The previous step failed. Please check your build process."
+
+      # Always display a message on completion
+      - name: Final step
+        run: echo "Build process completed."
