Update explore_actions.yml

diff --git a/.github/workflows/explore_actions.yml b/.github/workflows/explore_actions.yml
--- a/.github/workflows/explore_actions.yml
+++ b/.github/workflows/explore_actions.yml
@@ -35,13 +35,10 @@ jobs:
 
       # Introduce a step to simulate an error
       - name: Simulate a failure
-        run: exit 1
+        run: |
+          echo "::error step failed. Please check your build process."
+          exit 1
         continue-on-error: true
-
-      # Handle the error message based on the previous step
-      - name: Error message on failure
-        if: ${{ steps.simulate_failure.outcome == 'failure' }}   # Only runs if the previous step fails
-        run: echo "::error The previous step failed. Please check your build process."
 
       # Always display a message on completion
       - name: Final step
